import type { Locale } from './types';
const en = {
  instruction:'Explore first. A single tap places your guess and reveals the summit.', place:'Tap once to make your guess',
  revealing:'Following your guess…', sectionError:'The section could not be loaded. Your guess is saved; retry to reveal it.',
  section:'SOIUSA SECTION', rightSection:'Right section', outsideSection:'Outside the summit’s section', distancePoints:'Distance points', areaPoints:'Section bonus',
  howText:'Each day, find one Easy, one Medium and one Hard summit, in that order, using satellite imagery. Explore, then click once: your guess is locked and the summit is revealed.',
  howScore:'Distance earns up to 1,000 points. A guess inside the summit’s SOIUSA section also earns 15% of the remaining points. Difficulty describes identification, not climbing.',
  curveTitle:'How points work', curveDistance:'Distance only', curveSection:'In the right section', curveHint:'Move the slider to compare the scores. The section bonus applies only inside the summit’s actual boundary.',
};
export const interactionMessages: Record<Locale, typeof en> = {
  en,
  de:{instruction:'Erkunde zuerst die Karte. Ein Tippen setzt deinen Tipp und enthüllt den Gipfel.',place:'Einmal tippen, um zu raten',revealing:'Deinem Tipp auf der Spur…',sectionError:'Der Abschnitt konnte nicht geladen werden. Dein Tipp ist gespeichert; versuche es erneut.',section:'SOIUSA-ABSCHNITT',rightSection:'Richtiger Abschnitt',outsideSection:'Außerhalb des Gipfelabschnitts',distancePoints:'Entfernungspunkte',areaPoints:'Abschnittsbonus',howText:'Finde jeden Tag drei Gipfel anhand von Satellitenbildern: zuerst Leicht, dann Mittel, dann Schwer. Erkunde die Karte und klicke einmal: Dein Tipp steht fest und der Gipfel wird enthüllt.',howScore:'Die Entfernung bringt bis zu 1.000 Punkte. Ein Tipp im SOIUSA-Abschnitt des Gipfels erhält zusätzlich 15 % der verbleibenden Punkte. Schwierigkeit bedeutet Erkennen, nicht Klettern.',curveTitle:'So entstehen die Punkte',curveDistance:'Nur Entfernung',curveSection:'Im richtigen Abschnitt',curveHint:'Bewege den Regler, um die Punkte zu vergleichen. Der Bonus gilt nur innerhalb der tatsächlichen Abschnittsgrenze.'},
  fr:{instruction:'Explorez d’abord. Un seul toucher place votre repère et révèle le sommet.',place:'Touchez une fois pour jouer',revealing:'Sur la trace de votre repère…',sectionError:'La section n’a pas pu être chargée. Votre repère est enregistré ; réessayez pour révéler le sommet.',section:'SECTION SOIUSA',rightSection:'Bonne section',outsideSection:'Hors de la section du sommet',distancePoints:'Points de distance',areaPoints:'Bonus de section',howText:'Chaque jour, retrouvez un sommet facile, un moyen et un difficile, dans cet ordre, grâce aux images satellites. Explorez, puis cliquez une fois : votre choix est fixé et le sommet est révélé.',howScore:'La distance rapporte jusqu’à 1 000 points. Un repère dans la section SOIUSA du sommet gagne aussi 15 % des points restants. La difficulté concerne l’identification, pas l’ascension.',curveTitle:'Comment fonctionnent les points',curveDistance:'Distance seule',curveSection:'Dans la bonne section',curveHint:'Déplacez le curseur pour comparer les scores. Le bonus s’applique uniquement dans les limites réelles de la section du sommet.'},
  it:{instruction:'Esplora prima la mappa. Un solo tocco piazza la tua scelta e rivela la vetta.',place:'Tocca una volta per giocare',revealing:'Sulle tracce della tua scelta…',sectionError:'Impossibile caricare la sezione. La tua scelta è salvata; riprova per rivelare la vetta.',section:'SEZIONE SOIUSA',rightSection:'Sezione giusta',outsideSection:'Fuori dalla sezione della vetta',distancePoints:'Punti distanza',areaPoints:'Bonus sezione',howText:'Ogni giorno, trova una vetta facile, una media e una difficile, in questo ordine, usando le immagini satellitari. Esplora, poi clicca una volta: la scelta è definitiva e la vetta viene rivelata.',howScore:'La distanza vale fino a 1.000 punti. Una scelta nella sezione SOIUSA della vetta guadagna anche il 15% dei punti rimanenti. La difficoltà riguarda il riconoscimento, non la scalata.',curveTitle:'Come funzionano i punti',curveDistance:'Solo distanza',curveSection:'Nella sezione giusta',curveHint:'Sposta il cursore per confrontare i punteggi. Il bonus vale solo entro i confini reali della sezione della vetta.'},
};

export const resultMessages: Record<Locale, { keepResult: string }> = {
  en: { keepResult: 'Next view appears automatically after 6 seconds.' },
  de: { keepResult: 'Nach 6 Sekunden geht es automatisch weiter.' },
  fr: { keepResult: 'La suite apparaît automatiquement après 6 secondes.' },
  it: { keepResult: 'Si prosegue automaticamente dopo 6 secondi.' },
};
