import type {Locale} from './types';
const en={
 'alpine-peaks':'Alpine Peaks','world-peaks':'Worldwide Peaks','alpine-valleys':'Alpine Valleys',mode:'Game mode',alpineGroup:'Alps',worldGroup:'Worldwide',
 findVolcano:'Where is this volcano?',findPeak:'Where is this mountain?',findValley:'Where is this valley?',range:'MOUNTAIN REGION',valley:'VALLEY',
 valleyInstruction:'Explore first. One tap locks your guess and reveals the valley outline.',
 worldHelp:'Three mountains or volcanoes worldwide: Easy → Medium → Hard. One tap locks your guess. Guesses within 10 km get full points; distance points then decrease gently to 10 at 2,000 km; the right GMBA mountain region adds 15% of the remaining points. The next view appears automatically after 6 seconds.',
 regionTolerance:'The region bonus also applies up to 10 km outside the displayed GMBA outline.',
 valleyHelp:'Three Alpine valleys: Easy → Medium → Hard. Tap inside the named valley area for 1,000 points. Outside guesses are scored by distance to its boundary, with full points within 1 km and a gentle falloff beyond. The next view appears automatically after 6 seconds.',
 unavailable:'This catalogue is not ready yet.',unavailableHint:'This mode opens after its geographic data and all three difficulty levels have been verified.',
 inside:'Inside the valley',outside:'Outside the valley',boundaryDistance:'DISTANCE TO VALLEY',regionBonus:'Region bonus',
 geometryError:'The boundary could not be loaded. Your guess is saved. Retry to reveal the result.',summary:'Your daily results',complete:'DAILY CHALLENGE COMPLETE',credits:'Sources and boundaries',
 valleyDefinition:'The outline is the named geographic area supplied by the source; it can include surrounding slopes.',
};
export const modeMessages:Record<Locale,typeof en>={en,
 fr:{regionTolerance:'Le bonus de région s’applique aussi jusqu’à 10 km à l’extérieur du contour GMBA affiché.',valleyInstruction:'Explorez d’abord. Un toucher fixe votre choix et révèle le contour de la vallée.','alpine-peaks':'Sommets des Alpes','world-peaks':'Sommets du monde','alpine-valleys':'Vallées des Alpes',mode:'Mode de jeu',alpineGroup:'Alpes',worldGroup:'Monde',findVolcano:'Où se trouve ce volcan ?',findPeak:'Où se trouve cette montagne ?',findValley:'Où se trouve cette vallée ?',range:'RÉGION MONTAGNEUSE',valley:'VALLÉE',worldHelp:'Trois montagnes ou volcans du monde : facile → moyen → difficile. Un toucher valide votre choix. À moins de 10 km, vous gagnez tous les points ; ensuite ils diminuent doucement jusqu’à 10 à 2 000 km ; la bonne région GMBA ajoute 15 % des points restants. La suite apparaît automatiquement après 6 secondes.',valleyHelp:'Trois vallées alpines : facile → moyen → difficile. Touchez dans la vallée nommée pour gagner 1 000 points. À l’extérieur, la distance à sa limite détermine les points, avec tous les points à moins de 1 km et une baisse douce au-delà. La suite apparaît automatiquement après 6 secondes.',unavailable:'Ce catalogue n’est pas encore prêt.',unavailableHint:'Ce mode sera disponible après vérification des données géographiques et des trois niveaux de difficulté.',inside:'Dans la vallée',outside:'Hors de la vallée',boundaryDistance:'DISTANCE À LA VALLÉE',regionBonus:'Bonus de région',geometryError:'La limite n’a pas pu être chargée. Votre choix est enregistré. Réessayez pour voir le résultat.',summary:'Vos résultats du jour',complete:'DÉFI DU JOUR TERMINÉ',credits:'Sources et limites',valleyDefinition:'Le contour correspond à la zone géographique nommée par la source ; il peut inclure les versants environnants.'},
 de:{regionTolerance:'Der Regionsbonus gilt auch bis zu 10 km außerhalb der angezeigten GMBA-Grenze.',valleyInstruction:'Erkunde zuerst die Karte. Ein Tippen setzt deinen Tipp und zeigt die Talgrenze.','alpine-peaks':'Alpengipfel','world-peaks':'Gipfel weltweit','alpine-valleys':'Alpentäler',mode:'Spielmodus',alpineGroup:'Alpen',worldGroup:'Weltweit',findVolcano:'Wo liegt dieser Vulkan?',findPeak:'Wo liegt dieser Berg?',findValley:'Wo liegt dieses Tal?',range:'GEBIRGSREGION',valley:'TAL',worldHelp:'Drei Berge oder Vulkane weltweit: Leicht → Mittel → Schwer. Ein Tippen legt den Tipp fest. Bis 10 km gibt es volle Punkte; danach sinken sie sanft auf 10 bei 2.000 km; die richtige GMBA-Region bringt 15 % der übrigen Punkte. Nach 6 Sekunden geht es automatisch weiter.',valleyHelp:'Drei Alpentäler: Leicht → Mittel → Schwer. Ein Tipp im benannten Talgebiet bringt 1.000 Punkte. Außerhalb zählt die Entfernung zur Grenze mit vollen Punkten bis 1 km und einem sanften Rückgang danach. Nach 6 Sekunden geht es automatisch weiter.',unavailable:'Dieser Katalog ist noch nicht bereit.',unavailableHint:'Dieser Modus wird nach Prüfung der Geodaten und aller drei Schwierigkeitsstufen verfügbar.',inside:'Im Tal',outside:'Außerhalb des Tals',boundaryDistance:'ENTFERNUNG ZUM TAL',regionBonus:'Regionsbonus',geometryError:'Die Grenze konnte nicht geladen werden. Dein Tipp ist gespeichert. Versuche es erneut.',summary:'Dein Tagesergebnis',complete:'TAGESAUFGABE ABGESCHLOSSEN',credits:'Quellen und Grenzen',valleyDefinition:'Die Umrisse entsprechen dem benannten Gebiet der Quelle und können umliegende Hänge einschließen.'},
 it:{regionTolerance:'Il bonus regione vale anche fino a 10 km al di fuori del contorno GMBA visualizzato.',valleyInstruction:'Esplora prima. Un tocco conferma la scelta e rivela il contorno della valle.','alpine-peaks':'Vette alpine','world-peaks':'Vette del mondo','alpine-valleys':'Valli alpine',mode:'Modalità di gioco',alpineGroup:'Alpi',worldGroup:'Mondo',findVolcano:'Dove si trova questo vulcano?',findPeak:'Dove si trova questa montagna?',findValley:'Dove si trova questa valle?',range:'REGIONE MONTUOSA',valley:'VALLE',worldHelp:'Tre montagne o vulcani nel mondo: facile → medio → difficile. Un tocco conferma la scelta. Entro 10 km ottieni tutti i punti; poi diminuiscono gradualmente fino a 10 a 2.000 km; la regione GMBA corretta aggiunge il 15% dei punti restanti. Si prosegue automaticamente dopo 6 secondi.',valleyHelp:'Tre valli alpine: facile → medio → difficile. Tocca nell’area della valle per ottenere 1.000 punti. All’esterno conta la distanza dal confine, con tutti i punti entro 1 km e un calo graduale oltre. Si prosegue automaticamente dopo 6 secondi.',unavailable:'Questo catalogo non è ancora pronto.',unavailableHint:'La modalità sarà disponibile dopo la verifica dei dati geografici e dei tre livelli di difficoltà.',inside:'Dentro la valle',outside:'Fuori dalla valle',boundaryDistance:'DISTANZA DALLA VALLE',regionBonus:'Bonus regione',geometryError:'Impossibile caricare il confine. La scelta è salvata. Riprova per vedere il risultato.',summary:'I tuoi risultati del giorno',complete:'SFIDA DEL GIORNO COMPLETATA',credits:'Fonti e confini',valleyDefinition:'Il contorno rappresenta l’area geografica denominata dalla fonte e può includere i versanti circostanti.'},
};
