import type { Locale } from './types';
const en = {
  welcome: 'Welcome to AlpTap', mode: 'Game mode', dailyMode: 'Daily challenge',
  intro: 'Three summits each day. Find them on the satellite map.',
  steps: ['Read the summit name and its Alpine section.', 'Drag and zoom to explore. One tap locks your guess and reveals the summit.', 'See your distance and points. Compare the markers, then continue when ready.'],
  example: 'Try an example · Mont Blanc', exampleText: 'Take a free shot at Mont Blanc. Explore the mountains near Chamonix, then tap where you think the summit is.',
  tryExample: 'Try Mont Blanc on the map', practiceMode: 'Free practice', practiceDone: 'Start the daily challenge',
  practice: 'This example does not count towards your daily score.', start: 'Try Mont Blanc on the map', instructions: 'How to play',
};
export const onboardingMessages: Record<Locale, typeof en> = {
  en,
  fr: {welcome:'Bienvenue sur AlpTap',mode:'Mode de jeu',dailyMode:'Défi du jour',intro:'Trois sommets chaque jour. Retrouvez-les sur la carte satellite.',steps:['Lisez le nom du sommet et sa section alpine.', 'Déplacez et zoomez la carte. Un seul toucher valide votre choix et révèle le sommet.', 'Découvrez votre distance et vos points. Comparez les repères, puis continuez à votre rythme.'],example:'Un exemple · Mont Blanc',exampleText:'Imaginez que vous cherchez le Mont Blanc. Explorez les montagnes près de Chamonix, puis touchez l’endroit où vous pensez trouver le sommet.',tryExample:'Essayer le Mont Blanc sur la carte',practiceMode:'Essai gratuit',practiceDone:'Commencer le défi du jour',practice:'Cet exemple ne compte pas dans votre score du jour.',start:'Essayer le Mont Blanc sur la carte',instructions:'Comment jouer'},
  de: {welcome:'Willkommen bei AlpTap',mode:'Spielmodus',dailyMode:'Tägliche Herausforderung',intro:'Jeden Tag drei Gipfel. Finde sie auf der Satellitenkarte.',steps:['Lies den Gipfelnamen und seinen Alpenabschnitt.', 'Verschiebe und zoome die Karte. Ein Tippen legt deinen Tipp fest und enthüllt den Gipfel.', 'Sieh dir Entfernung und Punkte an. Vergleiche die Markierungen und gehe weiter, wenn du bereit bist.'],example:'Ein Beispiel · Mont Blanc',exampleText:'Stell dir vor, du suchst den Mont Blanc. Erkunde die Berge bei Chamonix und tippe dorthin, wo du den Gipfel vermutest.',tryExample:'Mont Blanc auf der Karte suchen',practiceMode:'Kostenlose Übungsrunde',practiceDone:'Tagesaufgabe starten',practice:'Dieses Beispiel zählt nicht zu deinem Tagesergebnis.',start:'Mont Blanc auf der Karte suchen',instructions:'Spielanleitung'},
  it: {welcome:'Benvenuto su AlpTap',mode:'Modalità di gioco',dailyMode:'Sfida del giorno',intro:'Tre vette ogni giorno. Trovale sulla mappa satellitare.',steps:['Leggi il nome della vetta e la sua sezione alpina.', 'Sposta e ingrandisci la mappa. Un solo tocco conferma la scelta e rivela la vetta.', 'Scopri distanza e punti. Confronta i segnaposto, poi prosegui quando vuoi.'],example:'Un esempio · Monte Bianco',exampleText:'Immagina di cercare il Monte Bianco. Esplora le montagne vicino a Chamonix, poi tocca dove pensi che si trovi la vetta.',tryExample:'Prova il Monte Bianco sulla mappa',practiceMode:'Prova gratuita',practiceDone:'Inizia la sfida del giorno',practice:'Questo esempio non conta nel punteggio giornaliero.',start:'Prova il Monte Bianco sulla mappa',instructions:'Come giocare'},
};
export const languageNames: Record<Locale, string> = {en:'English',de:'Deutsch',fr:'Français',it:'Italiano'};
